"""
============================================================
    Marvellous SmartHire AI Agent
============================================================

Author       : Piyush Manohar Khairnar
Date         : 10/05/2026

Description  :
This file contains the core intelligence of the
AI Mock Interview Agent.

This module is responsible for:

1. Creating prompts for LLM
2. Sending answers for evaluation
3. Receiving intelligent feedback
4. Extracting interview score
5. Maintaining interview history
6. Calculating overall performance
7. Generating final interview report
============================================================
"""

# Import ask_llm function
# Used to communicate with Llama3 model
from llm_engine import ask_llm

class MockInterviewAgent:
    """
    ============================================================
                    MockInterviewAgent Class
    ============================================================

    Description:
    This class represents the AI Interview Agent.

    Responsibilities:
    1. Evaluate answers
    2. Maintain history
    3. Calculate scores
    4. Generate reports
    ============================================================
    """

    def __init__(self, student_name):
        """
        Function Name : __init__

        Description   :
        Constructor of MockInterviewAgent class.

        Initializes:
        1. Student name
        2. Interview history
        3. Total score
        """
        # Store student name
        self.student_name = student_name

        # Stores complete interview history
        self.history = []

        # Stores total accumulated score
        self.total_score = 0

    def evaluate_answer(self, topic, question, answer):
        """
        Function Name : evaluate_answer

        Description   :
        Sends student answer to LLM for evaluation.

        Parameters    :
            topic    : Interview topic
            question : Interview question
            answer   : Student answer

        Return Value :
            Returns evaluation generated by LLM
        """

        print("\n================================================")
        print("Generating Prompt for LLM...")
        print("================================================")

        # Prompt Engineering
        # Creating structured prompt for Llama3
        prompt = f"""
You are an expert technical interviewer from Marvellous Infosystems.

Evaluate the student's answer carefully.

Student Name: {self.student_name}
Topic: {topic}
Question: {question}
Student Answer: {answer}

Give response strictly in this format:

Score: <number out of 10>

Evaluation:
Write whether the answer is correct, partially correct, or incorrect.

Missing Points:
Mention important technical points missing in the answer.

Improved Answer:
Write a better answer in simple student-friendly language.

Interview Suggestion:
Give one practical suggestion to improve interview performance.
"""

        print("Prompt Generated Successfully.")
        print("Sending Prompt to LLM...\n")

        # Send prompt to LLM
        evaluation = ask_llm(prompt)

        print("LLM Evaluation Received Successfully.")

        # Extract numerical score from evaluation
        score = self.extract_score(evaluation)

        # Add score to total score
        self.total_score += score

        # Store complete interview information
        self.history.append({
            "topic": topic,
            "question": question,
            "answer": answer,
            "evaluation": evaluation,
            "score": score
        })

        print(f"Score Extracted Successfully : {score}/10")

        return evaluation

    def extract_score(self, evaluation):
        """
        Function Name : extract_score

        Description   :
        Extracts numerical score from LLM response.

        Example:
            Score: 7/10

        Output:
            7

        Parameters    :
            evaluation : LLM generated evaluation

        Return Value :
            Returns extracted score
        """

        try:
            # Split evaluation into multiple lines
            for line in evaluation.split("\n"):

                # Search for line containing score
                if "score" in line.lower():

                    # Replace special characters
                    words = line.replace("/", " ") \
                                .replace(":", " ") \
                                .split()

                    # Traverse words
                    for word in words:

                        # Check whether word is number
                        if word.isdigit():

                            score = int(word)

                            # Validate score range
                            if 0 <= score <= 10:
                                return score

            # Default score if extraction fails
            return 0

        except Exception as e:

            print("\nError while extracting score.")
            print("Error :", e)

            return 0

    def generate_final_report(self):
        """
        Function Name : generate_final_report

        Description   :
        Generates complete interview report.

        Includes:
        1. Student details
        2. Total score
        3. Average score
        4. Overall performance
        5. Question-wise analysis

        Return Value :
            Returns final formatted report
        """

        print("\n================================================")
        print("Generating Final Interview Report...")
        print("================================================")

        # Calculate total questions asked
        total_questions = len(self.history)

        # Calculate average score
        if total_questions == 0:
            average_score = 0
        else:
            average_score = self.total_score / total_questions

        # Create initial report
        report = f"""
============================================================
              Marvellous Infosystems
              AI Mock Interview Report
============================================================

Author       : Piyush Manohar Khairnar
Date         : 10/05/2026

Student Name : {self.student_name}

Total Questions Asked : {total_questions}
Total Score           : {self.total_score}
Average Score         : {average_score:.2f}/10

============================================================
                    Overall Performance
============================================================
"""

        # Performance analysis
        if average_score >= 8:
            report += (
                "Excellent performance.\n"
                "Student has strong technical clarity "
                "and communication skills.\n"
            )

        elif average_score >= 6:
            report += (
                "Good performance.\n"
                "Student should add more examples and "
                "technical depth in answers.\n"
            )

        elif average_score >= 4:
            report += (
                "Average performance.\n"
                "Student needs revision of core concepts.\n"
            )

        else:
            report += (
                "Needs improvement.\n"
                "Student should start with fundamentals "
                "and practice more interview questions.\n"
            )

        # Add detailed analysis section
        report += """
============================================================
              Detailed Question-wise Analysis
============================================================
"""

        # Add analysis of every question
        for index, item in enumerate(self.history, start=1):

            report += f"""
------------------------------------------------------------
Question Number : {index}

Topic    : {item['topic']}

Question :
{item['question']}

------------------------------------------------------------
Student Answer:
------------------------------------------------------------
{item['answer']}

------------------------------------------------------------
Extracted Score:
------------------------------------------------------------
{item['score']}/10

------------------------------------------------------------
LLM Evaluation:
------------------------------------------------------------
{item['evaluation']}
"""

        # Add ending footer
        report += f"""

============================================================
                Report Summary
============================================================

Generated By :
Marvellous_AI_Agent

============================================================
"""
        print("Final Report Generated Successfully.")

        return report