"""
============================================================
Marvellous SmartHire AI Agent
============================================================

File Name    : llm_engine.py
Author       : Piyush Manohar Khairnar
Date         : 10/05/2026

Description  :
This file is responsible for communication between
our Python AI Agent and the Large Language Model (LLM).

The file sends prompts to the locally running Llama3 model
through Ollama API and receives intelligent responses.

This module acts as a bridge between:

Python Application
        AND
Llama3 Large Language Model

Concepts Covered:
1. API Communication
2. LLM Integration
3. Prompt Transmission
4. Response Handling
5. Exception Handling
6. AI Agent Tool Calling

============================================================
"""

# Import requests library
# Used to send HTTP requests to Ollama API
import requests

def ask_llm(prompt):
    """
    Function Name : ask_llm

    Description   :
    This function sends the given prompt to the
    locally running Llama3 model through Ollama API
    and returns the generated response.

    Parameters    :
        prompt : Prompt generated by AI Agent

    Return Value :
        Returns response generated by Llama3 model
    """

    # URL of locally running Ollama API
    # Ollama server listens on port 11434
    url = "http://localhost:11434/api/generate"

    # Payload contains details sent to LLM
    payload = {
        # Name of LLM model
        "model": "llama3",

        # Prompt generated by AI Agent
        "prompt": prompt,

        # stream=False means complete response
        # will be returned at once
        "stream": False
    }

    try:
        print("\n================================================")
        print("Connecting to Ollama Llama3 Model...")
        print("Sending Prompt to LLM...")
        print("================================================")

        # Send POST request to Ollama API
        response = requests.post(url, json=payload)

        # Raise exception if request failed
        response.raise_for_status()

        print("LLM Processing Completed Successfully.")

        # Convert JSON response into Python dictionary
        data = response.json()

        # Extract actual LLM response
        llm_response = data.get(
            "response",
            "No response generated by LLM."
        )

        return llm_response

    except Exception as e:

        # Error handling block
        # Executes if Ollama or Llama3 is not working

        return f"""
============================================================
                    LLM CONNECTION ERROR
============================================================

Ollama or Llama3 is not running properly.

Please check the following points carefully:

1. Ollama is installed properly
2. Llama3 model is downloaded
3. Ollama server is running
4. Internet is not required for local execution
5. Port 11434 is available

============================================================
        Marvellous Infosystems
============================================================
"""