"""
File Name    : report_generator.py
Author       : Piyush Manohar Khairnar
Date         : 10/05/2026

Description  :
This file is responsible for generating and saving
final interview reports of students.

The generated report contains:
1. Student Information
2. Interview Evaluation
3. Technical Feedback
4. Score Analysis
5. Suggestions

The report is automatically stored inside the
'reports' folder with timestamp information.

============================================================
"""

# Import os module
# Used for folder and file operations
import os

# Import datetime module
# Used to generate timestamp for report file
import datetime


def save_report(student_name, report):
    """
    Function Name : save_report

    Description   :
    This function saves the final interview report
    into a text file inside the reports folder.

    Parameters    :
        student_name : Name of student
        report       : Final generated report

    Return Value :
        Returns generated filename
    """

    # Check whether reports folder exists
    # If not present, create it
    if not os.path.exists("reports"):
        os.mkdir("reports")

    # Generate current timestamp
    # Example:
    # 10_05_2026_18_30_45
    timestamp = datetime.datetime.now().strftime(
        "%d_%m_%Y_%H_%M_%S"
    )

    # Replace spaces with underscore
    # to avoid filename issues
    safe_name = student_name.replace(" ", "_")

    # Generate report filename
    # Marvellous_AI_Agent added in filename
    filename = (
        f"reports/"
        f"Marvellous_AI_Agent_"
        f"{safe_name}_"
        f"Interview_Report_"
        f"{timestamp}.txt"
    )

    # Open file in write mode
    with open(filename, "w", encoding="utf-8") as file:

        # Write branding header into report
        file.write("=" * 70 + "\n")
        file.write("              Marvellous Infosystems\n")
        file.write("              AI Mock Interview Agent\n")
        file.write("              Generated Interview Report\n")
        file.write("=" * 70 + "\n\n")

        file.write("Author : Piyush Manohar Khairnar\n")
        file.write("Date   : 10/05/2026\n")

        file.write("=" * 70 + "\n")
        file.write("                  STUDENT REPORT\n")
        file.write("=" * 70 + "\n\n")

        # Write actual interview report
        file.write(report)

        # Add ending footer
        file.write("\n\n")
        file.write("=" * 70 + "\n")
        file.write("Generated By : Marvellous_SmartHire AI_Agent\n")
        file.write("Creator      : Marvellous Infosystems\n")
        file.write("=" * 70 + "\n")

    print("\n================================================")
    print("Interview Report Generated Successfully")
    print("Report File :", filename)
    print("================================================")

    # Return generated filename
    return filename