# ============================================================
# Program 4 : Keras Tokenization
# Target:
# Use Keras Tokenizer to automatically create word index
# ============================================================

from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "food was good",
    "food was bad",
    "food was not good"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index

print("=" * 60)
print("        Marvellous Infosystems")
print("   RNN Applications - Program 4")
print("=" * 60)

print("Target of this Program:")
print("Convert words into numeric indices using Keras Tokenizer")
print("-" * 60)

print("Word Index Generated by Tokenizer:")
for word, index in word_index.items():
    print(f"{word:10s} ---> {index}")

print("-" * 60)
print("Conclusion:")
print("Tokenizer assigns one unique number to every unique word.")