import numpy as np

np.set_printoptions(precision=3, suppress=True)

print("=" * 70)
print("        Marvellous Infosystems")
print("        Simple Transformer Decoder Demonstration")
print("=" * 70)

# ------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------

def softmax(row):
    exp_row = np.exp(row - np.max(row))
    return exp_row / exp_row.sum()

def layer_norm(X):
    mean = X.mean(axis=1, keepdims=True)
    std = X.std(axis=1, keepdims=True)
    return (X - mean) / (std + 1e-6)

def positional_encoding(seq_len, d_model):
    PE = np.zeros((seq_len, d_model))

    for pos in range(seq_len):
        for i in range(0, d_model, 2):
            PE[pos, i] = np.sin(pos / (10000 ** (i / d_model)))

            if i + 1 < d_model:
                PE[pos, i + 1] = np.cos(pos / (10000 ** (i / d_model)))

    return PE

# ------------------------------------------------------------
# Step 1: Encoder Output
# This normally comes from Transformer Encoder
# ------------------------------------------------------------

encoder_words = ["I", "love", "AI"]

encoder_output = np.array([
    [ 1.101, -1.145,  0.865, -0.821],
    [-1.216,  0.931, -0.735,  1.020],
    [ 0.721, -0.989,  1.219, -0.951]
])

print("\nSTEP 1: Encoder Output")
print("-" * 70)

for word, vector in zip(encoder_words, encoder_output):
    print(f"{word:5s} -> {vector}")

print("\nMeaning:")
print("This is the context-aware output generated by the encoder.")
print("Decoder will use this information while generating output words.")

# ------------------------------------------------------------
# Step 2: Decoder Input Embeddings
# ------------------------------------------------------------

decoder_words = ["मला", "AI", "आवडतो"]

decoder_input = np.array([
    [1.0, 0.0, 0.0, 1.0],   # मला 
    [0.0, 1.0, 1.0, 0.0],   # AI
    [1.0, 1.0, 0.0, 0.0]    # आवडतो
])

print("\nSTEP 2: Decoder Input Embeddings")
print("-" * 70)

for word, vector in zip(decoder_words, decoder_input):
    print(f"{word:8s} -> {vector}")

print("\nMeaning:")
print("Decoder input represents previously generated output words.")
print("During training, the correct target sentence is shifted and given to decoder.")

# ------------------------------------------------------------
# Step 3: Add Positional Encoding
# ------------------------------------------------------------

PE = positional_encoding(seq_len=3, d_model=4)

decoder_input_with_position = decoder_input + PE

print("\nSTEP 3: Positional Encoding for Decoder")
print("-" * 70)

print("\nPositional Encoding")
print(PE)

print("\nDecoder Input + Positional Encoding")
print(decoder_input_with_position)

print("\nMeaning:")
print("Position information is added because decoder also needs word order.")

# ------------------------------------------------------------
# Step 4: Masked Self-Attention
# ------------------------------------------------------------

def masked_self_attention(X):
    print("\nSTEP 4: Masked Self-Attention")
    print("-" * 70)

    Wq = np.eye(4)
    Wk = np.eye(4)
    Wv = np.eye(4)

    Q = np.dot(X, Wq)
    K = np.dot(X, Wk)
    V = np.dot(X, Wv)

    print("\nQ Matrix")
    print(Q)

    print("\nK Matrix")
    print(K)

    print("\nV Matrix")
    print(V)

    scores = np.dot(Q, K.T)

    print("\nOriginal Scores = Q × K.T")
    print(scores)

    dk = K.shape[1]
    scaled_scores = scores / np.sqrt(dk)

    print("\nScaled Scores")
    print(scaled_scores)

    mask = np.triu(np.ones(scaled_scores.shape), k=1)

    print("\nMask Matrix")
    print(mask)

    masked_scores = scaled_scores.copy()
    masked_scores[mask == 1] = -1e9

    print("\nMasked Scores")
    print(masked_scores)

    attention_weights = np.array([softmax(row) for row in masked_scores])

    print("\nMasked Attention Weights")
    print(attention_weights)

    output = np.dot(attention_weights, V)

    print("\nMasked Self-Attention Output")
    print(output)

    print("\nMeaning:")
    print("Decoder cannot see future words.")
    print("For example, first word can attend only to itself.")

    return output

masked_attention_output = masked_self_attention(decoder_input_with_position)

# ------------------------------------------------------------
# Step 5: Add & Layer Normalization
# ------------------------------------------------------------

print("\nSTEP 5: Add & Layer Normalization after Masked Attention")
print("-" * 70)

add1 = decoder_input_with_position + masked_attention_output

print("\nAdd1 = Decoder Input + Masked Attention Output")
print(add1)

norm1 = layer_norm(add1)

print("\nNorm1")
print(norm1)

# ------------------------------------------------------------
# Step 6: Encoder-Decoder Attention
# ------------------------------------------------------------

def encoder_decoder_attention(decoder_X, encoder_output):
    print("\nSTEP 6: Encoder-Decoder Attention")
    print("-" * 70)

    print("\nImportant Difference:")
    print("Q comes from decoder.")
    print("K and V come from encoder.")

    Wq = np.eye(4)
    Wk = np.eye(4)
    Wv = np.eye(4)

    Q = np.dot(decoder_X, Wq)
    K = np.dot(encoder_output, Wk)
    V = np.dot(encoder_output, Wv)

    print("\nQ Matrix from Decoder")
    print(Q)

    print("\nK Matrix from Encoder")
    print(K)

    print("\nV Matrix from Encoder")
    print(V)

    scores = np.dot(Q, K.T)

    print("\nScores = Qdecoder × Kencoder.T")
    print(scores)

    dk = K.shape[1]
    scaled_scores = scores / np.sqrt(dk)

    print("\nScaled Scores")
    print(scaled_scores)

    attention_weights = np.array([softmax(row) for row in scaled_scores])

    print("\nEncoder-Decoder Attention Weights")
    print(attention_weights)

    output = np.dot(attention_weights, V)

    print("\nEncoder-Decoder Attention Output")
    print(output)

    print("\nMeaning:")
    print("Decoder uses encoder output to understand which input words are important.")
    print("This connects target sentence generation with source sentence meaning.")

    return output

enc_dec_attention_output = encoder_decoder_attention(norm1, encoder_output)

# ------------------------------------------------------------
# Step 7: Add & Layer Normalization
# ------------------------------------------------------------

print("\nSTEP 7: Add & Layer Normalization after Encoder-Decoder Attention")
print("-" * 70)

add2 = norm1 + enc_dec_attention_output

print("\nAdd2 = Norm1 + Encoder-Decoder Attention Output")
print(add2)

norm2 = layer_norm(add2)

print("\nNorm2")
print(norm2)

# ------------------------------------------------------------
# Step 8: Feed Forward Network
# ------------------------------------------------------------

def feed_forward(X):
    print("\nSTEP 8: Feed Forward Network")
    print("-" * 70)

    W1 = np.array([
        [0.2, 0.4, 0.1, 0.3],
        [0.5, 0.1, 0.6, 0.2],
        [0.3, 0.7, 0.2, 0.5],
        [0.6, 0.2, 0.4, 0.1]
    ])

    W2 = np.array([
        [0.3, 0.2, 0.5, 0.1],
        [0.6, 0.4, 0.2, 0.3],
        [0.1, 0.7, 0.3, 0.5],
        [0.2, 0.1, 0.6, 0.4]
    ])

    hidden = np.dot(X, W1)

    print("\nDense Layer 1 Output")
    print(hidden)

    relu_output = np.maximum(0, hidden)

    print("\nAfter ReLU")
    print(relu_output)

    output = np.dot(relu_output, W2)

    print("\nDense Layer 2 Output")
    print(output)

    print("\nMeaning:")
    print("Feed Forward Network refines each output word representation.")

    return output

ff_output = feed_forward(norm2)

# ------------------------------------------------------------
# Step 9: Add & Layer Normalization Again
# ------------------------------------------------------------

print("\nSTEP 9: Add & Layer Normalization after Feed Forward")
print("-" * 70)

add3 = norm2 + ff_output

print("\nAdd3 = Norm2 + Feed Forward Output")
print(add3)

decoder_output = layer_norm(add3)

print("\nFinal Decoder Output")
print(decoder_output)

# ------------------------------------------------------------
# Step 10: Linear + Softmax Output Prediction
# ------------------------------------------------------------

print("\nSTEP 10: Linear Layer + Softmax Prediction")
print("-" * 70)

vocabulary = ["मला", "AI", "आवडतो", "शिकतो", "खातो"]

W_linear = np.array([
    [0.5, 0.2, 0.1, 0.3, 0.4],
    [0.1, 0.6, 0.2, 0.4, 0.1],
    [0.3, 0.1, 0.7, 0.2, 0.5],
    [0.2, 0.4, 0.1, 0.6, 0.3]
])

logits = np.dot(decoder_output, W_linear)

print("\nLogits")
print(logits)

probabilities = np.array([softmax(row) for row in logits])

print("\nProbabilities after Softmax")
print(probabilities)

print("\nPredicted Word at Each Position")
for i, row in enumerate(probabilities):
    predicted_index = np.argmax(row)
    print(f"Position {i + 1}: {vocabulary[predicted_index]}")
