# ============================================================
# Program 11 : Embedding Layer using Keras
# Target:
# Demonstrate Keras Embedding layer output
# ============================================================

import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

sentences = [
    "food was good",
    "food was bad",
    "food was not good"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

max_length = 4

X = pad_sequences(sequences, maxlen=max_length, padding="pre")

vocab_size = len(tokenizer.word_index) + 1

embedding_model = Sequential()
embedding_model.add(Embedding(input_dim=vocab_size, output_dim=4))
embedding_model.build(input_shape=(None, max_length))

print("=" * 60)
print("        Marvellous Infosystems")
print("   RNN Applications - Program 11")
print("=" * 60)

print("Target of this Program:")
print("Observe vector output generated by Embedding layer")
print("-" * 60)

embedding_model.summary()

embedding_output = embedding_model.predict(X, verbose=0)

print("\nInput Padded Sequences:")
print(X)

print("\nEmbedding Output Shape:", embedding_output.shape)
print("Shape means: samples, time_steps, embedding_vector_size")

print("\nEmbedding vectors for first sentence:")
print("Sentence:", sentences[0])
print("Padded Sequence:", X[0])
print("-" * 60)

for position, token in enumerate(X[0]):
    print("Position:", position + 1)
    print("Token   :", token)
    print("Vector  :", np.round(embedding_output[0][position], 4))
